"""empty message

Revision ID: 007ca01b0b8f
Revises: fd827b4640a5
Create Date: 2023-03-24 10:39:04.186341

"""
from operator import and_

from alembic import op
import sqlalchemy as sa

from application import db
from apps.api.models import RegionStatus

# revision identifiers, used by Alembic.
revision = '007ca01b0b8f'
down_revision = 'fd827b4640a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_timestamp', sa.DateTime(), nullable=True))

    for status in RegionStatus.query.order_by(RegionStatus.id):

        last_status = RegionStatus.query.filter(and_(RegionStatus.region_id == status.region_id, RegionStatus.id > status.id)).first()

        if last_status:
            status.end_timestamp = last_status.timestamp
            db.session.add(status)
            db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions_status', schema=None) as batch_op:
        batch_op.drop_column('end_timestamp')

    # ### end Alembic commands ###
